services:
  wagapi:
    build: .
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - wagapi_data:/data
    environment:
      - WAGAPI_API_KEY=${WAGAPI_API_KEY:-ProductionSecretDynamicTunnelAPIKeyCredentialToken}
      - WAGAPI_DATA_DIR=/data/test
      - PORT=${PORT:-8000}

volumes:
  wagapi_data:
