services:
  wagapi:
    build: .
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - wagapi_data:/data
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - WAGAPI_API_KEY=${WAGAPI_API_KEY:-ProductionSecretDynamicTunnelAPIKeyCredentialToken}
      - WAGAPI_DATA_DIR=/data
      - PORT=${PORT:-8000}
    # devices:
    #   - /dev/net/tun:/dev/net/tun
    # # sysctls:
      # - net.ipv4.ip_forward=1
      # - net.ipv6.conf.all.forwarding=1

volumes:
  wagapi_data:
